name: Golang DevOps
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  GOLANG: 1.22.2
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANG }}
      - name: Install golangci-lint + yamlfmt
        run: make install
      - name: Golang tests
        run: make test
      - name: Perform lint checks
        run: make lint
  git-actions:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANG }}
      - name: Install golang dependencies
        run: make install
      - name: Test repository
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: make test
